
[ClassVersion("1.0.0.0"), FriendlyName("VirtualHardDisk")]
class DSC_VirtualHardDisk : OMI_BaseResource
{
    [Key, Description("Specifies the full path to the virtual disk file that will be created or attached. This may or may not include the extension, but the extension must match the disk format.")] String FilePath;
    [Write, Description("Specifies the size the of virtual disk.")] Uint64 DiskSize;
    [Write, Description("Specifies the disk type the virtual disk should use."), ValueMap{"fixed","dynamic"}, Values{"fixed","dynamic"}] String DiskType;
    [Write, Description("Specifies the disk format the virtual disk should use. Defaults to vhdx."), ValueMap{"vhd","vhdx"}, Values{"vhd","vhdx"}] String DiskFormat;
    [Write, Description("Determines whether the virtual disk should be created and mounted or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
