ConvertFrom-StringData @'
    GettingDiskMessage = Getting disk with {0} '{1}' status for drive letter '{2}'.
    SettingDiskMessage = Setting disk with {0} '{1}' status for drive letter '{2}'.
    SetDiskOnlineMessage = Setting disk with {0} '{1}' online.
    SetDiskReadWriteMessage = Setting disk with {0} '{1}' to read/write.
    CheckingDiskPartitionStyleMessage = Checking disk with {0} '{1}' partition style.
    InitializingDiskMessage = Initializing disk with {0} '{1}' as '{2}'.
    DiskAlreadyInitializedMessage = Disk with {0} '{1}' is already initialized with '{2}'.
    CreatingPartitionMessage = Creating partition on disk with {0} '{1}' with drive letter '{2}' using {3}.
    FormattingVolumeMessage = Formatting the volume as '{0}'.
    SuccessfullyInitializedMessage = Successfully initialized '{0}'.
    AssigningDriveLetterMessage = Assigning drive letter '{0}'.
    ChangingVolumeLabelMessage = Changing volume '{0}' label to '{1}'.
    NewPartitionIsReadOnlyMessage = New partition '{2}' on disk with {0} '{1}' is readonly. Waiting for it to become writable.
    TestingDiskMessage = Testing disk with {0} '{1}' status for drive letter '{2}'.
    CheckDiskInitializedMessage = Checking if disk with {0} '{1}' is initialized.
    DiskNotFoundMessage = Disk with {0} '{1}' was not found.
    DiskNotOnlineMessage = Disk with {0} '{1}' is not online.
    DiskReadOnlyMessage = Disk with {0} '{1}' is readonly.
    DiskPartitionStyleNotMatchMessage = Disk with {0} '{1}' is initialized with partition style '{2}' but '{3}' is required.
    DiskInitializedWithWrongPartitionStyleError = Disk with {0} '{1}' is already initialized with partition style '{2}' but '{3}' is required. Set AllowDestructive and ClearDisk to $true to allow disk to be reinitialized.
    DriveLetterNotFoundMessage = Drive {0} was not found.
    SizeMismatchMessage = Partition assigned to drive {0} has size {1}, which does not match expected size {2}. Set AllowDestructive to $true to enable resizing of partition.
    SizeMismatchWithAllowDestructiveMessage = Partition assigned to drive {0} has size {1}, which does not match expected size {2}.
    AllocationUnitSizeMismatchMessage = Volume assigned to drive {0} has allocation unit size {1} KB does not match expected allocation unit size {2} KB.
    FileSystemFormatMismatch = Volume assigned to drive {0} filesystem format '{1}' does not match expected format '{2}'.
    DriveLabelMismatch = Volume assigned to drive {0} label '{1}' does not match expected label '{2}'.
    PartitionAlreadyAssignedMessage = Partition '{1}' is already assigned as drive {0}.
    MatchingPartitionNotFoundMessage = Disk with {0} '{1}' already contains partitions, but none match required size.
    MatchingPartitionNoSizeMessage = Disk with {0} '{1}' already contains partitions, but size parameter is not specified.
    SearchForVolumeMessage = Searching for {3} volume with no drive letter on partition '{2}' disk with {0} '{1}'.
    VolumeFoundMessage = Found {3} volume with no drive letter on partition '{2}' disk with {0} '{1}'.
    MatchingPartitionFoundMessage = Disk with {0} '{1}' already contains partitions, and partition '{2}' matches required size.
    DriveNotFoundOnPartitionMessage = Disk with {0} '{1}' does not contain a partition assigned to drive letter '{2}'.
    ClearingDiskMessage = Clearing disk with {0} '{1}' of all existing partitions and volumes.
    NewParitionIsReadOnlyError = New partition '{2}' on disk with {0} '{1}' did not become writable in the expected time.
    VolumeFormatInProgressMessage = Switch AllowDestructive is specified. Attempting to format volume on {0} with '{2}', was '{1}'.
    SizeMismatchCorrectionMessage = Switch AllowDestructive is specified. Attempting to resize partition {0} from {1} to {2}.
    FreeSpaceViolationError = Attempted to resize partition {0} from {1} to {2} while maximum allowed size was {3}.
    ResizeRefsNotPossibleMessage = Skipping resize of {0} from {1} to {2}. Resizing ReFS partitions is currently not possible.
    ResizeNotAllowedMessage = Skipping resize of {0} from {1} to {2}. AllowDestructive is not set to $true.
    AllowDestructiveNeededForDevDriveOperation = The partition with drive letter '{0}' was found to be big enough to be resized to create enough space for a new Dev Drive volume. However the 'AllowDestructive' flag was not set to $true.
    ResizingPartitionToMakeSpaceForDevDriveVolume = Resizing partition with drive letter '{0}' to size '{1} Gb', so we can make enough unallocated space for a Dev Drive volume of size '{2} Gb'.
    SuccessfullyConfiguredDevDriveVolume = The volume on drive '{0}:\\' has been successfully configured as a Dev Drive volume.
    FailedToConfigureDevDriveVolume = Failed to configure volume on drive '{0}:\\' as a Dev Drive volume.
    AttemptingToFindAPartitionToResizeForDevDrive = Attempting to find a partition that we can resize, in order to create enough unallocated space for a new Dev Drive volume.
    CheckingIfPartitionCanBeResizedForDevDrive = Checking if partition with drive letter '{0}' can be resized to create enough unallocated space for the new Dev Drive volume.
    PartitionCantBeResizedForDevDrive = Partition with drive letter '{0}' cannot be resized to create the new Dev Drive volume. Continuing search...
    PartitionFoundThatCanBeResizedForDevDrive = Found partition with drive letter '{0}' which can be resized to create a new Dev Drive volume.
    FoundNoPartitionsThatCanResizedForDevDrive = There is no unallocated space available to create the Dev Drive volume. We found no partitions that could be resized to create '{0} Gb' of unallocated space.
    NoPartitionResizeNeededForDevDrive = We found enough unallocated space available on the disk. No partition resize is needed to create the Dev Drive volume.
'@
